name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: v0.0.2
      - name: Install && Configuration
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install wget
      - name: Get GeoLite2 DBs
        run: |
          bash download.bash ASN ${{ secrets.AccountID }} ${{ secrets.LicenseKey }}
          bash download.bash City ${{ secrets.AccountID }} ${{ secrets.LicenseKey }}
          bash download.bash Country ${{ secrets.AccountID }} ${{ secrets.LicenseKey }}
      - name: Commit files
        env:
          TZ: Asia/Shanghai
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Auto Sync `date -R` - [Skip GitHub Action]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
